### ISSUE TITLE
Exercise 2.11

### ISSUE THREAD

**Issue by flor14** [juliasilge/supervised-ML-case-studies-course#10]
Dataset c2_testing_one_percent.rds is missing or has another name. Also, it is never used in the exercises 2.11 part 1 and 2

**Comment by juliasilge** [comment]
Aaaaah, it is missing because, yes, in fact, it is never used. I believe I originally intended to include it just to **show** that the student would in fact need to make a testing set in a realistic situation, but that doesn't seem necessary to me now. I will remove the loading of the testing dataset.
