### ISSUE TITLE
Which tests do/do not work?

### ISSUE THREAD

**Issue by juliasilge** [juliasilge/supervised-ML-case-studies-course#18]
Hello @flor14! I have been going through the course, fixing various bits. I am noticing that various tests do not currently work, but I can't tell what it is about the tests that lead them to not work. Do you know? It doesn't seem like it is single vs. double quotes, or emoji? Do you have other ideas?

**Comment by flor14** [comment]
Hello!

After your email, I made the packages modifications into install.R.  The problem was that installing directly e1017 make binder fail. Happy to hear that is solved with the last modifications I did.

I also noticed the problem with the tests. I tried changing double-quotes/single quotes too. I agree that emojis do not seem to be the problem as other tests with emojis worked. 
One test I tried stop failing after deleting it and then adding again Ines test template file. Maybe is something in the way tests are written. I'll keep trying. 

Best,
Julia

Sent from Mail for Windows 10

From: Julia Silge
Sent: lunes, 2 de septiembre de 2019 4:53 p. m.
To: juliasilge/supervised-ML-case-studies-course
Cc: flor14; Mention
Subject: [juliasilge/supervised-ML-case-studies-course] Which tests do/do notwork? (#18)

Hello @flor14! I have been going through the course, fixing various bits. I am noticing that various tests do not currently work, but I can't tell what it is about the tests that lead them to not work. Do you know? It doesn't seem like it is single vs. double quotes, or emoji? Do you have other ideas?

**Comment by juliasilge** [comment]
Things are working pretty well! Think I've got this figured out. 👍
